name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t waadmin/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true waadmin/react-test npm test

      - run: docker build -t waadmin/multi-client-10-14 ./client
      - run: docker build -t waadmin/multi-nginx-10-14 ./nginx
      - run: docker build -t waadmin/multi-server-10-14 ./server
      - run: docker build -t waadmin/multi-worker-10-14 ./worker

      - run: docker push waadmin/multi-client-10-14
      - run: docker push waadmin/multi-nginx-10-14
      - run: docker push waadmin/multi-server-10-14
      - run: docker push waadmin/multi-worker-10-14
